language: csharp
solution: metais.sln
install:
  - nuget restore metais.sln
  - nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug metais.sln
  - ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./metais-test/bin/Debug/MetaIS_Test.dll
  
