language: csharp
solution: metais.sln
install:
  - nuget restore metais.sln
  - nuget install nunit-console
script:
  - xbuild /p:Configuration=Debug metais.sln
  - nunit-console metais/bin/Debug/MetaIS.dll