language: csharp
script:
  - xbuild /p:Configuration=Debug metais.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore metais.sln
after_script:
  - nunit-console metais/bin/Debug/MetaIS.dll